//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personal_Accounting_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_income
    {
        public int SL_No { get; set; }
        public string source_type { get; set; }
        public int amount { get; set; }
        public System.DateTime date { get; set; }
        public int total { get; set; }
    }
}
